services:
  server:
    build:
      context: . # Build from the current directory
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes # The append-only file is an alternative, fully-durable strategy for Redis
